version: '3.8'
services:
  eureka-server:
    container_name: eureka-server
    build:
      context: eureka-server
      dockerfile: Dockerfile
    image: eureka-server
    ports:
      - "7070:7070"
  microservice-attraction:
    container_name: microservice-attraction
    build:
      context: microservice-attraction
      dockerfile: Dockerfile
    image: microservice-attraction
    ports:
      - "8084:8084"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:7070/eureka
  microservice-rewards:
    container_name: microservice-rewards
    build:
      context: microservice-rewards
      dockerfile: Dockerfile
    image: microservice-rewards
    ports:
      - "8085:8085"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:7070/eureka
  microservice-tracker:
    container_name: microservice-tracker
    build:
      context: microservice-tracker
      dockerfile: Dockerfile
    image: microservice-tracker
    ports:
      - "8082:8082"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:7070/eureka
  microservice-tripPricer:
    container_name: microservice-trippricer
    build:
      context: microservice-tripPricer
      dockerfile: Dockerfile
    image: microservice-trippricer
    ports:
      - "8086:8086"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:7070/eureka
  microservice-user:
    container_name: microservice-user
    build:
      context: microservice-user
      dockerfile: Dockerfile
    image: microservice-user
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:7070/eureka
  microservice-userLocation:
    container_name: microservice-userlocation
    build:
      context: microservice-userLocation
      dockerfile: Dockerfile
    image: microservice-userlocation
    ports:
      - "8083:8083"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:7070/eureka

