version: '3.8'
services:
  eureka-server:
    build:
      context: /Users/idrissi/Workspace/tourGuideMicroservices/eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    image: eureka-server:latest
    ports:
      - published: 7070
        target: 7070
  microservice-attraction:
    build:
      context: /Users/idrissi/Workspace/tourGuideMicroservices/microservice-attraction
      dockerfile: Dockerfile
    container_name: microservice-attraction
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:7070/eureka
    image: microservice-attraction:latest
    ports:
      - published: 8084
        target: 8084
  microservice-rewards:
    build:
      context: /Users/idrissi/Workspace/tourGuideMicroservices/microservice-rewards
      dockerfile: Dockerfile
    container_name: microservice-rewards
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:7070/eureka
    image: microservice-rewards:latest
    ports:
      - published: 8085
        target: 8085
  microservice-tracker:
    build:
      context: /Users/idrissi/Workspace/tourGuideMicroservices/microservice-tracker
      dockerfile: Dockerfile
    container_name: microservice-tracker
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:7070/eureka
    image: microservice-tracker:latest
    ports:
      - published: 8082
        target: 8082
  microservice-tripPricer:
    build:
      context: /Users/idrissi/Workspace/tourGuideMicroservices/microservice-tripPricer
      dockerfile: Dockerfile
    container_name: microservice-trippricer
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:7070/eureka
    image: microservice-trippricer:latest
    ports:
      - published: 8086
        target: 8086
  microservice-user:
    build:
      context: microservice-user
      dockerfile: Dockerfile
    container_name: microservice-user
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:7070/eureka
    image: microservice-user:latest
    ports:
      - published: 8081
        target: 8081
  microservice-userLocation:
    build:
      context: /Users/idrissi/Workspace/tourGuideMicroservices/microservice-userLocation
      dockerfile: Dockerfile
    container_name: microservice-userlocation
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:7070/eureka
    image: microservice-userlocation:latest
    ports:
      - published: 8083
        target: 8083


